// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMXxYSUNe2Zv0mNUzKlognu2qQxNoIp5E',
    appId: '1:769025686694:web:c0533f8ab190c1e56f8867',
    messagingSenderId: '769025686694',
    projectId: 'little-neck',
    authDomain: 'little-neck.firebaseapp.com',
    storageBucket: 'little-neck.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-E1qe-U-jvyceHXTrLqjTUjbScwt3rrA',
    appId: '1:769025686694:android:41cd6be0db0d7df96f8867',
    messagingSenderId: '769025686694',
    projectId: 'little-neck',
    storageBucket: 'little-neck.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBATXqnxPU3-Sc1YYo8TLs2FKQt9XkrBCo',
    appId: '1:769025686694:ios:dec6e8912a9dca1a6f8867',
    messagingSenderId: '769025686694',
    projectId: 'little-neck',
    storageBucket: 'little-neck.appspot.com',
    iosClientId: '769025686694-ad4lqbh5pni42g9bs29bbs0hakm324bj.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
